2015/04/09 14:38:54 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not allowed to access this page.' in /var/www/yii-1.1.16.bca042/framework/gii/GiiModule.php:170
Stack trace:
#0 /var/www/yii-1.1.16.bca042/framework/web/CController.php(263): GiiModule->beforeControllerAction(Object(DefaultController), Object(CInlineAction))
#1 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(282): CController->run('')
#2 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#3 /var/www/yii-1.1.16.bca042/framework/base/CApplication.php(184): CWebApplication->processRequest()
#4 /var/www/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/gii
---
2015/04/09 15:01:53 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: could not find driver' in /var/www/yii-1.1.16.bca042/framework/db/CDbConnection.php:399
Stack trace:
#0 /var/www/yii-1.1.16.bca042/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /var/www/yii-1.1.16.bca042/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /var/www/yii-1.1.16.bca042/framework/base/CModule.php(394): CDbConnection->init()
#3 /var/www/yii-1.1.16.bca042/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /var/www/yii-1.1.16.bca042/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /var/www/yii-1.1.16.bca042/framework/web/CFormModel.php(39): ModelCode->init()
#6 /var/www/yii-1.1.16.bca042/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /var/www/yii-1.1.16.bca042/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /var/www/yii-1.1.16.bca042/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /var/www/yii-1.1.16.bca042/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /var/www/yii-1.1.16.bca042/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/yii-1.1.16.bca042/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(282): CController->run('index')
#13 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /var/www/yii-1.1.16.bca042/framework/base/CApplication.php(184): CWebApplication->processRequest()
#15 /var/www/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/gii/model/index
HTTP_REFERER=http://104.236.5.192/gii/default/index
---
2015/04/09 16:08:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "goods".' in /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(141): CWebApplication->runController('goods')
#1 /var/www/yii-1.1.16.bca042/framework/base/CApplication.php(184): CWebApplication->processRequest()
#2 /var/www/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/goods/
---
2015/04/09 16:31:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "rom-0".' in /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(141): CWebApplication->runController('rom-0')
#1 /var/www/yii-1.1.16.bca042/framework/base/CApplication.php(184): CWebApplication->processRequest()
#2 /var/www/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rom-0
---
2015/04/09 16:36:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "trial".' in /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(141): CWebApplication->runController('trial')
#1 /var/www/yii-1.1.16.bca042/framework/base/CApplication.php(184): CWebApplication->processRequest()
#2 /var/www/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/trial
---
2015/04/09 16:36:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "trial/trial".' in /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(141): CWebApplication->runController('trial/trial')
#1 /var/www/yii-1.1.16.bca042/framework/base/CApplication.php(184): CWebApplication->processRequest()
#2 /var/www/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/trial/trial
---
2015/04/09 16:36:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "trial/trial".' in /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(141): CWebApplication->runController('trial/trial')
#1 /var/www/yii-1.1.16.bca042/framework/base/CApplication.php(184): CWebApplication->processRequest()
#2 /var/www/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/trial/trial
---
2015/04/09 16:37:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "Trial".' in /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(141): CWebApplication->runController('Trial')
#1 /var/www/yii-1.1.16.bca042/framework/base/CApplication.php(184): CWebApplication->processRequest()
#2 /var/www/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Trial
---
2015/04/09 16:39:15 [error] [exception.CException] exception 'CException' with message 'DenemeController cannot find the requested view "index".' in /var/www/yii-1.1.16.bca042/framework/web/CController.php:878
Stack trace:
#0 /var/www/yii-1.1.16.bca042/framework/web/CController.php(782): CController->renderPartial('index', NULL, true)
#1 /var/www/protected/controllers/DenemeController.php(32): CController->render('index')
#2 /var/www/yii-1.1.16.bca042/framework/web/actions/CInlineAction.php(49): DenemeController->actionIndex()
#3 /var/www/yii-1.1.16.bca042/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /var/www/yii-1.1.16.bca042/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /var/www/yii-1.1.16.bca042/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(282): CController->run('')
#7 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(141): CWebApplication->runController('deneme')
#8 /var/www/yii-1.1.16.bca042/framework/base/CApplication.php(184): CWebApplication->processRequest()
#9 /var/www/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/deneme
---
2015/04/09 16:40:14 [error] [php] include(REST.php): failed to open stream: No such file or directory (/var/www/yii-1.1.16.bca042/framework/YiiBase.php:432)
Stack trace:
#0 /var/www/protected/controllers/DenemeController.php(9): spl_autoload_call()
#1 /var/www/yii-1.1.16.bca042/framework/web/actions/CInlineAction.php(49): DenemeController->actionIndex()
#2 /var/www/yii-1.1.16.bca042/framework/web/CController.php(308): CInlineAction->runWithParams()
#3 /var/www/yii-1.1.16.bca042/framework/web/CController.php(286): DenemeController->runAction()
#4 /var/www/yii-1.1.16.bca042/framework/web/CController.php(265): DenemeController->runActionWithFilters()
#5 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(282): DenemeController->run()
#6 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(141): CWebApplication->runController()
#7 /var/www/yii-1.1.16.bca042/framework/base/CApplication.php(184): CWebApplication->processRequest()
#8 /var/www/index.php(13): CWebApplication->run()
REQUEST_URI=/deneme
in /var/www/protected/controllers/DenemeController.php (9)
in /var/www/index.php (13)
2015/04/10 07:55:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "manager/html".' in /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(141): CWebApplication->runController('manager/html')
#1 /var/www/yii-1.1.16.bca042/framework/base/CApplication.php(184): CWebApplication->processRequest()
#2 /var/www/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/manager/html
---
2015/04/10 11:14:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "testproxy.php".' in /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(141): CWebApplication->runController('testproxy.php')
#1 /var/www/yii-1.1.16.bca042/framework/base/CApplication.php(184): CWebApplication->processRequest()
#2 /var/www/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=http://testp3.pospr.waw.pl/testproxy.php
---
2015/04/10 17:29:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "rom-0".' in /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(141): CWebApplication->runController('rom-0')
#1 /var/www/yii-1.1.16.bca042/framework/base/CApplication.php(184): CWebApplication->processRequest()
#2 /var/www/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rom-0
---
2015/04/10 20:46:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "testproxy.php".' in /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(141): CWebApplication->runController('testproxy.php')
#1 /var/www/yii-1.1.16.bca042/framework/base/CApplication.php(184): CWebApplication->processRequest()
#2 /var/www/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=http://testp4.pospr.waw.pl/testproxy.php
---
2015/04/11 16:13:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "api/newUser".' in /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(141): CWebApplication->runController('api/newUser')
#1 /var/www/yii-1.1.16.bca042/framework/base/CApplication.php(184): CWebApplication->processRequest()
#2 /var/www/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/api/newUser
---
2015/04/11 16:13:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "api/newUser".' in /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(141): CWebApplication->runController('api/newUser')
#1 /var/www/yii-1.1.16.bca042/framework/base/CApplication.php(184): CWebApplication->processRequest()
#2 /var/www/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/api/newUser
---
2015/04/11 16:19:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 /var/www/yii-1.1.16.bca042/framework/base/CApplication.php(184): CWebApplication->processRequest()
#2 /var/www/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2015/04/11 16:20:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "api/NewUser".' in /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(141): CWebApplication->runController('api/NewUser')
#1 /var/www/yii-1.1.16.bca042/framework/base/CApplication.php(184): CWebApplication->processRequest()
#2 /var/www/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/api/NewUser
---
2015/04/11 16:20:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "api/NewUser".' in /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(141): CWebApplication->runController('api/NewUser')
#1 /var/www/yii-1.1.16.bca042/framework/base/CApplication.php(184): CWebApplication->processRequest()
#2 /var/www/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/api/NewUser
---
2015/04/11 16:20:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 /var/www/yii-1.1.16.bca042/framework/base/CApplication.php(184): CWebApplication->processRequest()
#2 /var/www/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2015/04/11 16:22:54 [error] [php] Missing argument 1 for CHttpRequest::getPost(), called in /var/www/yii-1.1.16.bca042/framework/base/CComponent.php on line 111 and defined (/var/www/yii-1.1.16.bca042/framework/web/CHttpRequest.php:199)
Stack trace:
#0 /var/www/protected/controllers/ApiController.php(18): CHttpRequest->__call()
#1 /var/www/protected/controllers/ApiController.php(18): CHttpRequest->post()
#2 /var/www/yii-1.1.16.bca042/framework/web/actions/CInlineAction.php(49): ApiController->actionNewUser()
#3 /var/www/yii-1.1.16.bca042/framework/web/CController.php(308): CInlineAction->runWithParams()
#4 /var/www/yii-1.1.16.bca042/framework/web/CController.php(286): ApiController->runAction()
#5 /var/www/yii-1.1.16.bca042/framework/web/CController.php(265): ApiController->runActionWithFilters()
#6 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(282): ApiController->run()
#7 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(141): CWebApplication->runController()
#8 /var/www/yii-1.1.16.bca042/framework/base/CApplication.php(184): CWebApplication->processRequest()
#9 /var/www/index.php(13): CWebApplication->run()
REQUEST_URI=/api/NewUser
in /var/www/protected/controllers/ApiController.php (18)
in /var/www/protected/controllers/ApiController.php (18)
in /var/www/index.php (13)
2015/04/11 16:45:31 [error] [php] Illegal string offset 'latitude' (/var/www/protected/controllers/ApiController.php:34)
Stack trace:
#0 /var/www/yii-1.1.16.bca042/framework/web/CController.php(286): ApiController->runAction()
#1 /var/www/yii-1.1.16.bca042/framework/web/CController.php(265): ApiController->runActionWithFilters()
#2 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(282): ApiController->run()
#3 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(141): CWebApplication->runController()
#4 /var/www/yii-1.1.16.bca042/framework/base/CApplication.php(184): CWebApplication->processRequest()
#5 /var/www/index.php(13): CWebApplication->run()
REQUEST_URI=/api/NewUser
in /var/www/protected/controllers/ApiController.php (34)
in /var/www/index.php (13)
2015/04/11 16:46:49 [error] [php] Illegal string offset 'latitude' (/var/www/protected/controllers/ApiController.php:34)
Stack trace:
#0 /var/www/yii-1.1.16.bca042/framework/web/CController.php(286): ApiController->runAction()
#1 /var/www/yii-1.1.16.bca042/framework/web/CController.php(265): ApiController->runActionWithFilters()
#2 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(282): ApiController->run()
#3 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(141): CWebApplication->runController()
#4 /var/www/yii-1.1.16.bca042/framework/base/CApplication.php(184): CWebApplication->processRequest()
#5 /var/www/index.php(13): CWebApplication->run()
REQUEST_URI=/api/NewUser
in /var/www/protected/controllers/ApiController.php (34)
in /var/www/index.php (13)
2015/04/11 16:48:44 [error] [php] Undefined index: category_id (/var/www/protected/controllers/ApiController.php:41)
Stack trace:
#0 /var/www/yii-1.1.16.bca042/framework/web/CController.php(286): ApiController->runAction()
#1 /var/www/yii-1.1.16.bca042/framework/web/CController.php(265): ApiController->runActionWithFilters()
#2 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(282): ApiController->run()
#3 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(141): CWebApplication->runController()
#4 /var/www/yii-1.1.16.bca042/framework/base/CApplication.php(184): CWebApplication->processRequest()
#5 /var/www/index.php(13): CWebApplication->run()
REQUEST_URI=/api/NewUser
in /var/www/protected/controllers/ApiController.php (41)
in /var/www/index.php (13)
2015/04/11 16:51:57 [error] [php] Undefined variable: category (/var/www/protected/controllers/ApiController.php:40)
Stack trace:
#0 /var/www/yii-1.1.16.bca042/framework/web/CController.php(286): ApiController->runAction()
#1 /var/www/yii-1.1.16.bca042/framework/web/CController.php(265): ApiController->runActionWithFilters()
#2 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(282): ApiController->run()
#3 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(141): CWebApplication->runController()
#4 /var/www/yii-1.1.16.bca042/framework/base/CApplication.php(184): CWebApplication->processRequest()
#5 /var/www/index.php(13): CWebApplication->run()
REQUEST_URI=/api/NewUser
in /var/www/protected/controllers/ApiController.php (40)
in /var/www/index.php (13)
2015/04/11 16:54:57 [error] [exception.CException] exception 'CException' with message 'Property "Item.langtitude" is not defined.' in /var/www/yii-1.1.16.bca042/framework/base/CComponent.php:173
Stack trace:
#0 /var/www/yii-1.1.16.bca042/framework/db/ar/CActiveRecord.php(161): CComponent->__set('langtitude', -97.456)
#1 /var/www/protected/controllers/ApiController.php(45): CActiveRecord->__set('langtitude', -97.456)
#2 /var/www/yii-1.1.16.bca042/framework/web/actions/CInlineAction.php(49): ApiController->actionNewUser()
#3 /var/www/yii-1.1.16.bca042/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /var/www/yii-1.1.16.bca042/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /var/www/yii-1.1.16.bca042/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(282): CController->run('NewUser')
#7 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(141): CWebApplication->runController('api/NewUser')
#8 /var/www/yii-1.1.16.bca042/framework/base/CApplication.php(184): CWebApplication->processRequest()
#9 /var/www/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/api/NewUser
---
2015/04/11 16:55:49 [error] [php] Undefined index: longtitude (/var/www/protected/controllers/ApiController.php:39)
Stack trace:
#0 /var/www/yii-1.1.16.bca042/framework/web/CController.php(286): ApiController->runAction()
#1 /var/www/yii-1.1.16.bca042/framework/web/CController.php(265): ApiController->runActionWithFilters()
#2 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(282): ApiController->run()
#3 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(141): CWebApplication->runController()
#4 /var/www/yii-1.1.16.bca042/framework/base/CApplication.php(184): CWebApplication->processRequest()
#5 /var/www/index.php(13): CWebApplication->run()
REQUEST_URI=/api/NewUser
in /var/www/protected/controllers/ApiController.php (39)
in /var/www/index.php (13)
2015/04/11 16:56:28 [error] [exception.CException] exception 'CException' with message 'Property "Item.category_id" is not defined.' in /var/www/yii-1.1.16.bca042/framework/base/CComponent.php:173
Stack trace:
#0 /var/www/yii-1.1.16.bca042/framework/db/ar/CActiveRecord.php(161): CComponent->__set('category_id', 2)
#1 /var/www/protected/controllers/ApiController.php(55): CActiveRecord->__set('category_id', 2)
#2 /var/www/yii-1.1.16.bca042/framework/web/actions/CInlineAction.php(49): ApiController->actionNewUser()
#3 /var/www/yii-1.1.16.bca042/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /var/www/yii-1.1.16.bca042/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /var/www/yii-1.1.16.bca042/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(282): CController->run('NewUser')
#7 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(141): CWebApplication->runController('api/NewUser')
#8 /var/www/yii-1.1.16.bca042/framework/base/CApplication.php(184): CWebApplication->processRequest()
#9 /var/www/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/api/NewUser
---
2015/04/11 17:52:35 [error] [exception.CException] exception 'CException' with message 'Property "CDbCriteria.is_it_main" is not defined.' in /var/www/yii-1.1.16.bca042/framework/base/CComponent.php:173
Stack trace:
#0 /var/www/yii-1.1.16.bca042/framework/db/schema/CDbCriteria.php(160): CComponent->__set('is_it_main', 0)
#1 /var/www/yii-1.1.16.bca042/framework/db/schema/CDbCommandBuilder.php(588): CDbCriteria->__construct(Array)
#2 /var/www/yii-1.1.16.bca042/framework/db/ar/CActiveRecord.php(1769): CDbCommandBuilder->createCriteria(Array, Array)
#3 /var/www/protected/controllers/ApiController.php(145): CActiveRecord->updateAll('is_it_main=:is_...', Array)
#4 /var/www/yii-1.1.16.bca042/framework/web/actions/CInlineAction.php(49): ApiController->actionNewPicture()
#5 /var/www/yii-1.1.16.bca042/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#6 /var/www/yii-1.1.16.bca042/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#7 /var/www/yii-1.1.16.bca042/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(282): CController->run('NewPicture')
#9 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(141): CWebApplication->runController('api/NewPicture')
#10 /var/www/yii-1.1.16.bca042/framework/base/CApplication.php(184): CWebApplication->processRequest()
#11 /var/www/index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/api/NewPicture
---
2015/04/11 18:44:39 [error] [php] Undefined index: longtitude (/var/www/protected/controllers/ApiController.php:131)
Stack trace:
#0 /var/www/yii-1.1.16.bca042/framework/web/CController.php(286): ApiController->runAction()
#1 /var/www/yii-1.1.16.bca042/framework/web/CController.php(265): ApiController->runActionWithFilters()
#2 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(282): ApiController->run()
#3 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(141): CWebApplication->runController()
#4 /var/www/yii-1.1.16.bca042/framework/base/CApplication.php(184): CWebApplication->processRequest()
#5 /var/www/index.php(13): CWebApplication->run()
REQUEST_URI=/api/UpdateItem
in /var/www/protected/controllers/ApiController.php (131)
in /var/www/index.php (13)
2015/04/11 18:45:08 [error] [php] Undefined index: user_id (/var/www/protected/controllers/ApiController.php:137)
Stack trace:
#0 /var/www/yii-1.1.16.bca042/framework/web/CController.php(286): ApiController->runAction()
#1 /var/www/yii-1.1.16.bca042/framework/web/CController.php(265): ApiController->runActionWithFilters()
#2 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(282): ApiController->run()
#3 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(141): CWebApplication->runController()
#4 /var/www/yii-1.1.16.bca042/framework/base/CApplication.php(184): CWebApplication->processRequest()
#5 /var/www/index.php(13): CWebApplication->run()
REQUEST_URI=/api/UpdateItem
in /var/www/protected/controllers/ApiController.php (137)
in /var/www/index.php (13)
2015/04/11 19:08:23 [error] [php] Undefined variable: ites_liked (/var/www/protected/controllers/ApiController.php:518)
Stack trace:
#0 /var/www/yii-1.1.16.bca042/framework/web/CController.php(286): ApiController->runAction()
#1 /var/www/yii-1.1.16.bca042/framework/web/CController.php(265): ApiController->runActionWithFilters()
#2 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(282): ApiController->run()
#3 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(141): CWebApplication->runController()
#4 /var/www/yii-1.1.16.bca042/framework/base/CApplication.php(184): CWebApplication->processRequest()
#5 /var/www/index.php(13): CWebApplication->run()
REQUEST_URI=/api/LikeItem
in /var/www/protected/controllers/ApiController.php (518)
in /var/www/index.php (13)
2015/04/11 19:26:12 [error] [php] Undefined index: items_liked_id (/var/www/protected/controllers/ApiController.php:563)
Stack trace:
#0 /var/www/yii-1.1.16.bca042/framework/web/CController.php(286): ApiController->runAction()
#1 /var/www/yii-1.1.16.bca042/framework/web/CController.php(265): ApiController->runActionWithFilters()
#2 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(282): ApiController->run()
#3 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(141): CWebApplication->runController()
#4 /var/www/yii-1.1.16.bca042/framework/base/CApplication.php(184): CWebApplication->processRequest()
#5 /var/www/index.php(13): CWebApplication->run()
REQUEST_URI=/api/UnlikeItem
in /var/www/protected/controllers/ApiController.php (563)
in /var/www/index.php (13)
2015/04/11 20:06:32 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-2' for key 'follower'. The SQL statement executed was: INSERT INTO `profile_follows` (`follower`, `followed`, `date`) VALUES (:yp0, :yp1, NOW()).
in /var/www/protected/controllers/ApiController.php (631)
in /var/www/index.php (13)
2015/04/11 20:06:32 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-2' for key 'follower'. The SQL statement executed was: INSERT INTO `profile_follows` (`follower`, `followed`, `date`) VALUES (:yp0, :yp1, NOW())' in /var/www/yii-1.1.16.bca042/framework/db/CDbCommand.php:358
Stack trace:
#0 /var/www/yii-1.1.16.bca042/framework/db/ar/CActiveRecord.php(1080): CDbCommand->execute()
#1 /var/www/yii-1.1.16.bca042/framework/db/ar/CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 /var/www/protected/controllers/ApiController.php(631): CActiveRecord->save()
#3 /var/www/yii-1.1.16.bca042/framework/web/actions/CInlineAction.php(49): ApiController->actionFollowProfile()
#4 /var/www/yii-1.1.16.bca042/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#5 /var/www/yii-1.1.16.bca042/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#6 /var/www/yii-1.1.16.bca042/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(282): CController->run('FollowProfile')
#8 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(141): CWebApplication->runController('api/FollowProfi...')
#9 /var/www/yii-1.1.16.bca042/framework/base/CApplication.php(184): CWebApplication->processRequest()
#10 /var/www/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/api/FollowProfile
---
2015/04/11 20:06:54 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-2' for key 'follower'. The SQL statement executed was: INSERT INTO `profile_follows` (`follower`, `followed`, `date`) VALUES (:yp0, :yp1, NOW()).
in /var/www/protected/controllers/ApiController.php (631)
in /var/www/index.php (13)
2015/04/11 20:06:54 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-2' for key 'follower'. The SQL statement executed was: INSERT INTO `profile_follows` (`follower`, `followed`, `date`) VALUES (:yp0, :yp1, NOW())' in /var/www/yii-1.1.16.bca042/framework/db/CDbCommand.php:358
Stack trace:
#0 /var/www/yii-1.1.16.bca042/framework/db/ar/CActiveRecord.php(1080): CDbCommand->execute()
#1 /var/www/yii-1.1.16.bca042/framework/db/ar/CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 /var/www/protected/controllers/ApiController.php(631): CActiveRecord->save()
#3 /var/www/yii-1.1.16.bca042/framework/web/actions/CInlineAction.php(49): ApiController->actionFollowProfile()
#4 /var/www/yii-1.1.16.bca042/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#5 /var/www/yii-1.1.16.bca042/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#6 /var/www/yii-1.1.16.bca042/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(282): CController->run('FollowProfile')
#8 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(141): CWebApplication->runController('api/FollowProfi...')
#9 /var/www/yii-1.1.16.bca042/framework/base/CApplication.php(184): CWebApplication->processRequest()
#10 /var/www/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/api/FollowProfile
---
2015/04/11 20:08:04 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-2' for key 'follower'. The SQL statement executed was: INSERT INTO `profile_follows` (`follower`, `followed`, `date`) VALUES (:yp0, :yp1, NOW()).
in /var/www/protected/controllers/ApiController.php (631)
in /var/www/index.php (13)
2015/04/11 20:08:04 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-2' for key 'follower'. The SQL statement executed was: INSERT INTO `profile_follows` (`follower`, `followed`, `date`) VALUES (:yp0, :yp1, NOW())' in /var/www/yii-1.1.16.bca042/framework/db/CDbCommand.php:358
Stack trace:
#0 /var/www/yii-1.1.16.bca042/framework/db/ar/CActiveRecord.php(1080): CDbCommand->execute()
#1 /var/www/yii-1.1.16.bca042/framework/db/ar/CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 /var/www/protected/controllers/ApiController.php(631): CActiveRecord->save()
#3 /var/www/yii-1.1.16.bca042/framework/web/actions/CInlineAction.php(49): ApiController->actionFollowProfile()
#4 /var/www/yii-1.1.16.bca042/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#5 /var/www/yii-1.1.16.bca042/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#6 /var/www/yii-1.1.16.bca042/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(282): CController->run('FollowProfile')
#8 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(141): CWebApplication->runController('api/FollowProfi...')
#9 /var/www/yii-1.1.16.bca042/framework/base/CApplication.php(184): CWebApplication->processRequest()
#10 /var/www/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/api/FollowProfile
---
2015/04/11 20:39:41 [error] [php] Undefined variable: item (/var/www/protected/controllers/ApiController.php:742)
Stack trace:
#0 /var/www/yii-1.1.16.bca042/framework/web/CController.php(286): ApiController->runAction()
#1 /var/www/yii-1.1.16.bca042/framework/web/CController.php(265): ApiController->runActionWithFilters()
#2 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(282): ApiController->run()
#3 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(141): CWebApplication->runController()
#4 /var/www/yii-1.1.16.bca042/framework/base/CApplication.php(184): CWebApplication->processRequest()
#5 /var/www/index.php(13): CWebApplication->run()
REQUEST_URI=/api/NewUser
in /var/www/protected/controllers/ApiController.php (742)
in /var/www/index.php (13)
2015/04/11 20:53:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "api/Login".' in /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(141): CWebApplication->runController('api/Login')
#1 /var/www/yii-1.1.16.bca042/framework/base/CApplication.php(184): CWebApplication->processRequest()
#2 /var/www/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/api/Login
---
2015/04/11 21:09:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "docs/funcspecs/3.jsp".' in /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(141): CWebApplication->runController('docs/funcspecs/...')
#1 /var/www/yii-1.1.16.bca042/framework/base/CApplication.php(184): CWebApplication->processRequest()
#2 /var/www/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/docs/funcspecs/3.jsp
HTTP_REFERER=http://65.74.153.170/docs/funcspecs/3.jsp
---
2015/04/11 21:25:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "api/GetFollowers".' in /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(141): CWebApplication->runController('api/GetFollower...')
#1 /var/www/yii-1.1.16.bca042/framework/base/CApplication.php(184): CWebApplication->processRequest()
#2 /var/www/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/api/GetFollowers
---
2015/04/11 21:29:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "GetFolloweds".' in /var/www/yii-1.1.16.bca042/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii-1.1.16.bca042/framework/web/CController.php(270): CController->missingAction('GetFolloweds')
#1 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(282): CController->run('GetFolloweds')
#2 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(141): CWebApplication->runController('api/GetFollowed...')
#3 /var/www/yii-1.1.16.bca042/framework/base/CApplication.php(184): CWebApplication->processRequest()
#4 /var/www/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/api/GetFolloweds
---
2015/04/11 21:29:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "GetFolloweds".' in /var/www/yii-1.1.16.bca042/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii-1.1.16.bca042/framework/web/CController.php(270): CController->missingAction('GetFolloweds')
#1 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(282): CController->run('GetFolloweds')
#2 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(141): CWebApplication->runController('api/GetFollowed...')
#3 /var/www/yii-1.1.16.bca042/framework/base/CApplication.php(184): CWebApplication->processRequest()
#4 /var/www/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/api/GetFolloweds
---
2015/04/11 21:29:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "GetFolloweds".' in /var/www/yii-1.1.16.bca042/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii-1.1.16.bca042/framework/web/CController.php(270): CController->missingAction('GetFolloweds')
#1 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(282): CController->run('GetFolloweds')
#2 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(141): CWebApplication->runController('api/GetFollowed...')
#3 /var/www/yii-1.1.16.bca042/framework/base/CApplication.php(184): CWebApplication->processRequest()
#4 /var/www/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/api/GetFolloweds
---
2015/04/11 21:29:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "GetFolloweds".' in /var/www/yii-1.1.16.bca042/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii-1.1.16.bca042/framework/web/CController.php(270): CController->missingAction('GetFolloweds')
#1 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(282): CController->run('GetFolloweds')
#2 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(141): CWebApplication->runController('api/GetFollowed...')
#3 /var/www/yii-1.1.16.bca042/framework/base/CApplication.php(184): CWebApplication->processRequest()
#4 /var/www/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/api/GetFolloweds
---
2015/04/11 21:29:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "GetFolloweds".' in /var/www/yii-1.1.16.bca042/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii-1.1.16.bca042/framework/web/CController.php(270): CController->missingAction('GetFolloweds')
#1 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(282): CController->run('GetFolloweds')
#2 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(141): CWebApplication->runController('api/GetFollowed...')
#3 /var/www/yii-1.1.16.bca042/framework/base/CApplication.php(184): CWebApplication->processRequest()
#4 /var/www/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/api/GetFolloweds
---
2015/04/11 21:29:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "GetFolloweds".' in /var/www/yii-1.1.16.bca042/framework/web/CController.php:483
Stack trace:
#0 /var/www/yii-1.1.16.bca042/framework/web/CController.php(270): CController->missingAction('GetFolloweds')
#1 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(282): CController->run('GetFolloweds')
#2 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(141): CWebApplication->runController('api/GetFollowed...')
#3 /var/www/yii-1.1.16.bca042/framework/base/CApplication.php(184): CWebApplication->processRequest()
#4 /var/www/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/api/GetFolloweds
---
2015/04/11 21:29:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "api/GetFolloweds".' in /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(141): CWebApplication->runController('api/GetFollowed...')
#1 /var/www/yii-1.1.16.bca042/framework/base/CApplication.php(184): CWebApplication->processRequest()
#2 /var/www/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/api/GetFolloweds
---
2015/04/11 21:30:01 [error] [php] Undefined variable: follower (/var/www/protected/controllers/ApiController.php:733)
Stack trace:
#0 /var/www/yii-1.1.16.bca042/framework/web/CController.php(286): ApiController->runAction()
#1 /var/www/yii-1.1.16.bca042/framework/web/CController.php(265): ApiController->runActionWithFilters()
#2 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(282): ApiController->run()
#3 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(141): CWebApplication->runController()
#4 /var/www/yii-1.1.16.bca042/framework/base/CApplication.php(184): CWebApplication->processRequest()
#5 /var/www/index.php(13): CWebApplication->run()
REQUEST_URI=/api/GetFolloweds
in /var/www/protected/controllers/ApiController.php (733)
in /var/www/index.php (13)
2015/04/11 21:30:02 [error] [php] Undefined variable: follower (/var/www/protected/controllers/ApiController.php:733)
Stack trace:
#0 /var/www/yii-1.1.16.bca042/framework/web/CController.php(286): ApiController->runAction()
#1 /var/www/yii-1.1.16.bca042/framework/web/CController.php(265): ApiController->runActionWithFilters()
#2 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(282): ApiController->run()
#3 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(141): CWebApplication->runController()
#4 /var/www/yii-1.1.16.bca042/framework/base/CApplication.php(184): CWebApplication->processRequest()
#5 /var/www/index.php(13): CWebApplication->run()
REQUEST_URI=/api/GetFolloweds
in /var/www/protected/controllers/ApiController.php (733)
in /var/www/index.php (13)
2015/04/11 21:30:03 [error] [php] Undefined variable: follower (/var/www/protected/controllers/ApiController.php:733)
Stack trace:
#0 /var/www/yii-1.1.16.bca042/framework/web/CController.php(286): ApiController->runAction()
#1 /var/www/yii-1.1.16.bca042/framework/web/CController.php(265): ApiController->runActionWithFilters()
#2 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(282): ApiController->run()
#3 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(141): CWebApplication->runController()
#4 /var/www/yii-1.1.16.bca042/framework/base/CApplication.php(184): CWebApplication->processRequest()
#5 /var/www/index.php(13): CWebApplication->run()
REQUEST_URI=/api/GetFolloweds
in /var/www/protected/controllers/ApiController.php (733)
in /var/www/index.php (13)
2015/04/11 21:38:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "api/GetUser".' in /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(141): CWebApplication->runController('api/GetUser')
#1 /var/www/yii-1.1.16.bca042/framework/base/CApplication.php(184): CWebApplication->processRequest()
#2 /var/www/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/api/GetUser
---
2015/04/12 00:44:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "manager/html".' in /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(141): CWebApplication->runController('manager/html')
#1 /var/www/yii-1.1.16.bca042/framework/base/CApplication.php(184): CWebApplication->processRequest()
#2 /var/www/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/manager/html
---
2015/04/12 11:09:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "cgi-bin/test-cgi".' in /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(141): CWebApplication->runController('cgi-bin/test-cg...')
#1 /var/www/yii-1.1.16.bca042/framework/base/CApplication.php(184): CWebApplication->processRequest()
#2 /var/www/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/cgi-bin/test-cgi
---
2015/04/12 11:18:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "_search".' in /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii-1.1.16.bca042/framework/web/CWebApplication.php(141): CWebApplication->runController('_search')
#1 /var/www/yii-1.1.16.bca042/framework/base/CApplication.php(184): CWebApplication->processRequest()
#2 /var/www/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/_search?pretty
---
